/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 vanguard_logo.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function VanguardLogo({position, onHandleAnimation}) {
  const { nodes, materials } = useGLTF("models/vanguard_logo.glb")

  return ( //TODO: Fix models so they are all the same orientation and size
    <group  
      scale={[.55,.55,.55]}
      position={position}
      center={position}
      rotation-x={3.7}
      dispose={null}
      onClick={() => onHandleAnimation()}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('models/vanguard_logo.glb')
