/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 vanguard_logo.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function VanguardLogo({ shouldRotate, ...props }) {
  const ref = useRef();

  useFrame(({clock}) => {
    if(shouldRotate) {
      const t = clock.getElapsedTime()
      ref.current.rotation.z = t
    }
  })

  const { nodes, materials } = useGLTF("models/vanguard_logo.glb")

  return (
    <group
      ref={ref}
      scale={[.55, .55, .55]}
      rotation-x={3.7}
      dispose={null}
      {...props}
    >
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('models/vanguard_logo.glb')
